config/routes.rb
Rails.application.routes.draw do
  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, length: { minimum: 1 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post # The before_action invokes the private method #find_post to ensure that we are creating a comment on the porper corresponding post

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(comment_params) # @post.comments.build(comment_params) makes use of the has_many relationship that the post model has and then builds a comment there, with the post_id assigned to the comment upon creation
    @comment.user_id = current_user.id # set the foreign key (user_id) of the comment to the current user's id so that the comment belongs to a user
    if @comment.save
      respond_to do |format|
       format.html { redirect_to root_path }
       format.js
      end
      create_notification(@post, @comment)
    else
      flash[:alert] = "Check the comment form, something went horribly wrong!"
      render root_path # not necessarily render :new because we don't want a comment form out there on its own view without it being attached to the post
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id]) # Due to the nature of comments being built or found through their association with the post model, this is the way to accurately reference the comment at hand
    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
       format.html { redirect_to root_path }
       format.js
      end
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def create_notification(post, comment)
    return if post.user.id == current_user.id
    Notification.create(user_id: post.user.id, notified_by_id: current_user.id, post_id: post.id, identifier: comment.id, notice_type: 'comment')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.username, profile_path(comment.user.username)
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { post_id: post.id, value: post.comments.count, confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do
      %span(class="glyphicon glyphicon-remove delete-comment-icon")

app/views/comments/create.js.erb
$('#comment_content_<%= @post.id %>').val('')
$('#comment_content_<%= @post.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);

if (Append.comment || Append.open ){ $('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>"); }
else if ((Append.comment && Append.open) === false && Append.link === true) {
	$('#comments_' + Append.post_id).append("<div class='paginator' id='#comments-paginator-" + Append.post_id + "'><a class='more-comments' id='more_comments_" + Append.post_id + "' data-post-id='" + Append.post_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/posts/" + Append.post_id + "/comments'>view all " + Append.comment_count + " comments</a></div>");
	ClickableCommentsLink();
}
else if ((Append.comment && Append.open && Append.link) === false) { $('#more_comments_<%= @post.id %>').html("View all <%= @post.comments.count %> comments"); }

// When a new comment is made, the view all comments count needs a refresh for it to work
// When comment on a post that is on another page (aka page 2 onward aka after load more), the destroy still holds up but the create comment with an AJAX call doesn't appear to render

app/views/comments/delete.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");
Append.comment_count -= 1

app/views/comments/index.html.haml
= render @comments, post: @post