config/routes.rb
Rails.application.routes.draw do
  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root "posts#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notified_by, class_name: "User"
  belongs_to :user
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :identifier, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path(@notification.post)
  end

  def index
    @notifications = current_user.notifications.order("created_at DESC")
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.haml
%li
  = link_to "#{notification.notified_by.username} has #{notification.notice_type}ed on your post", link_through_path(notification)
.time_ago_thing
  = time_ago_in_words(notification.created_at)
  ago

app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button.btn.btn-default.dropdown-toggle{ type: 'button', id: 'dropdownMenu1', data: { toggle: 'dropdown' }, 'aria-haspopup': true, 'aria-expanded': true }
    = current_user.notifications.where(read: false).count
    %span.glyphicon.glyphicon-flag
  %ul.dropdown-menu{ 'aria-labelledby': 'dropdownMenu1' }
    %li.dropdown-header.text-center Notifications
    = render current_user.notifications.where(read: false).order('created_at DESC').last(5)
    %li.divider{ role: 'separator' }
      %li.text-center= link_to 'View All', notifications_path

app/views/notifications/index.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %ul.notification-index-list
        - @notifications.each do |notification|
          = render 'notification', notification: notification

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>