config/routes.rb
Rails.application.routes.draw do
  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: { maximum: 300 }

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  scope :of_followed_users, -> (following_users) { where user_id: following_users }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:browse, :show]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.of_followed_users(current_user.following).order('created_at DESC').page(params[:page])
  end

  def browse
    @posts = Post.all.order('created_at DESC').page(params[:page])
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully updated."
      redirect_to @post
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post successfully deleted."
      redirect_to posts_path
    else
      flash.now[:alert] = "Post was not deleted; something went wrong."
    end
  end

  def like
    if @post.liked_by(current_user)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) } # { redirect_to :back} # Might have to do the fallback redirect
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by(current_user)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:caption, :image)
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up
    if votes.size <= 8
      return list_likers(votes)
    else
      count_likers(votes)
    end
  end

  def liked_post(post)
    if current_user.liked?(post)
      return 'glyphicon-heart'
    else
      return 'glyphicon-heart-empty'
    end
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.username, profile_path(voter.username), class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, input_html: { class: 'form-horizontal', multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image (this is required):
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption', input_html: { class: 'form-control' }
            .form-group.text-center
              = f.button :submit, class: "btn btn-success btn-block"

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes(post)

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.username, profile_path(post.user.username)
      .time-ago
        = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image, class: 'img-responsive'), post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            = link_to post.user.username, profile_path(post.user.username)
          = post.caption
        .comments{id: "comments_#{post.id}"}
          - if post.comments.any?
            = render post.comments.first(4), post: post
            - unless post.comments.count <= 4
              .paginator{id: "#comments-paginator-#{post.id}"}
                = link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html, value:" "#{post.comments.count}"}
    .comment-like-form.row
      .col-sm-1.like-button
        - if user_signed_in?
          - if current_user.liked?(post)
            = link_to '', unlike_post_path(post.id), remote: true, id: "like_#{post.id}", class: "like glyphicon #{liked_post(post)}"
          - else
            = link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "like glyphicon #{liked_post(post)}"
      .comment-form.col-sm-11
        - if user_signed_in?
          = form_for([post, post.comments.build], remote: true) do |f|
            = f.text_field :content, placeholder: "Add a comment...", class: "comment_content", id: "comment_content_#{post.id}"

app/views/posts/_post_dashboard.html.haml
#posts
  = render 'posts'

#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts,'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/_posts.html.haml
- @posts.each do |post|
  = render 'post', post: post

app/views/posts/browse.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "Cancel", posts_path

app/views/posts/index.html.haml
#posts
  = render 'post_dashboard', posts: @posts

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").attr("href", '/posts/<%= @post.id %>/unlike');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post } ) %>");

app/views/posts/likes.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart')

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render 'post', post: @post
.text-center.edit-links
  = link_to "Home", posts_path
  - if user_signed_in? && current_user.id == @post.user_id
    |
    = link_to "Edit", edit_post_path(@post)

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").attr("href", '/posts/<%= @post.id %>/like');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post } ) %>");